FROM rocker/r-ver:4.2
RUN R -e "install.packages('parallel', repos='http://cran.us.r-project.org')"
RUN R -e "install.packages('data.table', repos='http://cran.us.r-project.org')"
RUN R -e "install.packages('vroom', repos='http://cran.us.r-project.org')"
RUN R -e "install.packages('remotes', repos='http://cran.us.r-project.org')"
RUN R -e "install.packages('Rcpp', repos='http://cran.us.r-project.org')"
RUN R -e "install.packages('fst', repos='http://cran.us.r-project.org')"
RUN R -e "remotes::install_github('rqtl/qtl2')"
RUN R -e "remotes::install_github('rqtl/qtl2convert')"
RUN R -e "remotes::install_github('rqtl/qtl2fst')"
RUN R -e "remotes::install_github('byandell/qtl2ggplot',force = T)"
RUN R -e "remotes::install_github('kbroman/broman')"
RUN R -e "remotes::install_github('kbroman/qtlcharts')"
RUN R -e "install.packages('purrr')"
RUN R -e "install.packages('furrr',dependencies = T)"
RUN R -e "install.packages('dplyr')"
RUN R -e "install.packages('magrittr')"
RUN R -e "install.packages('ggplot2')"
RUN R -e "install.packages('ggbeeswarm')"
RUN R -e "install.packages('tidyr')"
