name: Build cosine similarity container (env/cossim.Dockerfile)

on:
  push:
    paths:
    - 'env/cossim.Dockerfile'
    - '.github/workflows/build_cossim_docker.yml'
  pull_request:
    paths:
    - 'env/cossim.Dockerfile'
    - '.github/workflows/build_cossim_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sjwidmay/lcGBS_HR
        username: ${{ secrets.SJW_DOCKER_USER }}
        password: ${{ secrets.SJW_DOCKER_PASS }}
        snapshot: true
        dockerfile: cossim.Dockerfile
        workdir: "env"
        tags: "cossim"
