name: Build main container (env/DO4WC_HR.Dockerfile)

on:
  push:
    paths:
    - 'env/lcGBS_bioconductor.Dockerfile'
    - '.github/workflows/build_bioconductor_docker.yml'
  pull_request:
    paths:
    - 'env/lcGBS_bioconductor.Dockerfile'
    - '.github/workflows/build_bioconductor_docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: sjwidmay/lcGBS_HR
        username: ${{ secrets.SJW_DOCKER_USER }}
        password: ${{ secrets.SJW_DOCKER_PASS }}
        snapshot: true
        dockerfile: lcGBS_bioconductor.Dockerfile
        workdir: "env"
        tags: "latest"
        cache: true